name: flutter_skeleton
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^9.0.0
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flag: ^7.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.5
  get_it: ^8.0.3
  intl: any
  shared_preferences: ^2.5.2
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
  # fonts:
  # - family: Roboto
  #   fonts:
  #     - asset: assets/fonts/Roboto-Regular.ttf
  #     - asset: assets/fonts/Roboto-Bold.ttf
  #       weight: 700
  # - family: Poppins
  #   fonts:
  #     - asset: assets/fonts/Poppins-Regular.ttf
  #     - asset: assets/fonts/Poppins-Bold.ttf
  #       weight: 700
  #     - asset: assets/fonts/Poppins-Black.ttf
  #       weight: 900
  #     - asset: assets/fonts/Poppins-Italic.ttf
  #       style: italic
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#42a5f5"
  background_image: "assets/images/logo.png"
  branding: "assets/images/logo.png"
  android_12:
    color: "#42a5f5"
    background_image: "assets/images/logo.png"
    branding: "assets/images/logo.png"
